"""
RAG 业务指标库 — 存储企业协作 SaaS 平台常用业务指标定义
每个指标包含：名称、别名（用户可能的问法）、SQL 模板、适用场景
这些指标会向量化存入 Milvus，帮助 LLM 理解用户的业务语言
"""

BUSINESS_METRICS = [
    # ─── 会议指标 ───────────────────────────────────────────────
    {
        "metric_id": "meeting_count",
        "metric_name": "会议总数",
        "aliases": ["开了多少会议", "会议数量", "总会议数", "开了几个会", "会议场次"],
        "sql_template": "SELECT COUNT(*) AS meeting_count FROM fact_meeting WHERE org_id = '{org_id}' AND meeting_status = 'ended' AND start_time >= '{start_date}' AND start_time < '{end_date}'",
        "definition_desc": "统计指定时间范围内已结束的会议总数",
        "unit": "场",
        "category": "会议",
        "table_used": ["fact_meeting"],
        "applicable_scenes": ["会议数量趋势", "各部门会议量对比", "同比环比"],
    },
    {
        "metric_id": "meeting_participants",
        "metric_name": "会议参会人数",
        "aliases": ["参会人数", "平均参会人数", "多少人参会", "参会人数平均"],
        "sql_template": "SELECT AVG(participant_count) AS avg_participants, SUM(participant_count) AS total_participants FROM fact_meeting WHERE org_id = '{org_id}' AND meeting_status = 'ended' AND start_time >= '{start_date}' AND start_time < '{end_date}'",
        "definition_desc": "会议的平均参会人数和总参会人次",
        "unit": "人/场",
        "category": "会议",
        "table_used": ["fact_meeting"],
        "applicable_scenes": ["参会规模分析", "会议参与度", "部门参会对比"],
    },
    {
        "metric_id": "avg_meeting_duration",
        "metric_name": "平均会议时长",
        "aliases": ["会议平均时长", "会议一般开多久", "会议时长", "平均开会时长", "每次会议多久"],
        "sql_template": "SELECT AVG(actual_duration_seconds) / 60.0 AS avg_duration_minutes FROM fact_meeting WHERE org_id = '{org_id}' AND meeting_status = 'ended' AND actual_duration_seconds IS NOT NULL AND actual_duration_seconds > 0 AND start_time >= '{start_date}' AND start_time < '{end_date}'",
        "definition_desc": "所有已结束会议的实际通话时长的平均值（分钟）",
        "unit": "分钟",
        "category": "会议",
        "table_used": ["fact_meeting"],
        "applicable_scenes": ["会议效率分析", "会议时长趋势", "部门对比"],
    },
    {
        "metric_id": "meeting_quality_score",
        "metric_name": "会议质量评分",
        "aliases": ["会议质量", "连接质量", "会议体验", "通话质量"],
        "sql_template": "SELECT AVG(quality_score) AS avg_quality_score, SUM(excellent_sessions) * 100.0 / NULLIF(SUM(total_sessions), 0) AS excellent_rate FROM fact_quality WHERE org_id = '{org_id}' AND session_type = 'meeting' AND record_date >= '{start_date}' AND record_date < '{end_date}'",
        "definition_desc": "会议连接质量综合评分（0-100）和优质率（excellent 会话占比）",
        "unit": "分（0-100）",
        "category": "会议质量",
        "table_used": ["fact_quality"],
        "applicable_scenes": ["会议体验监控", "网络质量分析", "问题溯源"],
    },
    {
        "metric_id": "total_meeting_duration",
        "metric_name": "会议总时长",
        "aliases": ["总会议时长", "累计会议时长", "所有会议加起来多久", "会议总时间"],
        "sql_template": "SELECT SUM(actual_duration_seconds) / 60.0 AS total_duration_minutes, SUM(actual_duration_seconds) / 3600.0 AS total_duration_hours FROM fact_meeting WHERE org_id = '{org_id}' AND meeting_status = 'ended' AND actual_duration_seconds IS NOT NULL AND start_time >= '{start_date}' AND start_time < '{end_date}'",
        "definition_desc": "所有已结束会议的实际通话时长总和（分钟/小时）",
        "unit": "分钟 / 小时",
        "category": "会议",
        "table_used": ["fact_meeting"],
        "applicable_scenes": ["会议资源消耗", "会议时间成本分析"],
    },
    {
        "metric_id": "screen_share_count",
        "metric_name": "屏幕共享次数",
        "aliases": ["共享屏幕次数", "屏幕分享次数", "有多少次屏幕共享"],
        "sql_template": "SELECT SUM(screen_share_count) AS total_screen_shares FROM fact_meeting WHERE org_id = '{org_id}' AND meeting_status = 'ended' AND screen_share_count IS NOT NULL AND start_time >= '{start_date}' AND start_time < '{end_date}'",
        "definition_desc": "所有会议中的屏幕共享总次数",
        "unit": "次",
        "category": "会议",
        "table_used": ["fact_meeting"],
        "applicable_scenes": ["协作活跃度", "演示使用频率"],
    },
    {
        "metric_id": "recording_usage",
        "metric_name": "会议录制使用率",
        "aliases": ["录制会议数", "录制了多少会议", "录制率", "有多少会议录了"],
        "sql_template": "SELECT COUNT(*) AS total_meetings, SUM(CASE WHEN is_recorded = TRUE THEN 1 ELSE 0 END) AS recorded_meetings, ROUND(SUM(CASE WHEN is_recorded = TRUE THEN 1 ELSE 0 END) * 100.0 / COUNT(*), 2) AS recording_rate FROM fact_meeting WHERE org_id = '{org_id}' AND meeting_status = 'ended' AND start_time >= '{start_date}' AND start_time < '{end_date}'",
        "definition_desc": "开启录制的会议数和录制率",
        "unit": "%",
        "category": "会议",
        "table_used": ["fact_meeting"],
        "applicable_scenes": ["录制功能使用情况", "合规记录需求分析"],
    },

    # ─── 通话指标 ───────────────────────────────────────────────
    {
        "metric_id": "call_count",
        "metric_name": "通话总数",
        "aliases": ["通话数量", "打了多少电话", "通话次数", "总通话数"],
        "sql_template": "SELECT COUNT(*) AS call_count FROM fact_calling WHERE org_id = '{org_id}' AND start_time >= '{start_date}' AND start_time < '{end_date}'",
        "definition_desc": "指定时间范围内的通话总次数（含已接/未接/呼出/呼入）",
        "unit": "通",
        "category": "通话",
        "table_used": ["fact_calling"],
        "applicable_scenes": ["通话量趋势", "各部门通话量对比"],
    },
    {
        "metric_id": "avg_call_duration",
        "metric_name": "平均通话时长",
        "aliases": ["通话平均时长", "每次通话多久", "电话平均时长", "通话一般多长"],
        "sql_template": "SELECT AVG(talk_duration_seconds) / 60.0 AS avg_talk_duration_minutes FROM fact_calling WHERE org_id = '{org_id}' AND talk_duration_seconds IS NOT NULL AND talk_duration_seconds > 0 AND start_time >= '{start_date}' AND start_time < '{end_date}'",
        "definition_desc": "所有已接通通话的实际通话时长的平均值（分钟）",
        "unit": "分钟",
        "category": "通话",
        "table_used": ["fact_calling"],
        "applicable_scenes": ["通话效率分析", "通话时长趋势"],
    },
    {
        "metric_id": "call_answer_rate",
        "metric_name": "通话接通率",
        "aliases": ["接通率", "接听率", "有多少电话接通了", "电话打通的比例"],
        "sql_template": "SELECT COUNT(*) AS total_calls, SUM(CASE WHEN call_status = 'completed' THEN 1 ELSE 0 END) AS answered_calls, ROUND(SUM(CASE WHEN call_status = 'completed' THEN 1 ELSE 0 END) * 100.0 / COUNT(*), 2) AS answer_rate FROM fact_calling WHERE org_id = '{org_id}' AND start_time >= '{start_date}' AND start_time < '{end_date}'",
        "definition_desc": "已接通通话数 / 总通话数，反映沟通响应效率",
        "unit": "%",
        "category": "通话",
        "table_used": ["fact_calling"],
        "applicable_scenes": ["响应效率", "部门接通率对比", "呼入/呼出接通率"],
    },
    {
        "metric_id": "missed_call_count",
        "metric_name": "未接来电数",
        "aliases": ["未接电话", "missed calls", "漏接电话", "没接到的电话"],
        "sql_template": "SELECT COUNT(*) AS missed_calls FROM fact_calling WHERE org_id = '{org_id}' AND call_status = 'missed' AND start_time >= '{start_date}' AND start_time < '{end_date}'",
        "definition_desc": "状态为 missed 的通话数量（响铃未接）",
        "unit": "通",
        "category": "通话",
        "table_used": ["fact_calling"],
        "applicable_scenes": ["漏接电话监控", "响应及时性"],
    },
    {
        "metric_id": "total_call_duration",
        "metric_name": "通话总时长",
        "aliases": ["累计通话时长", "总共打了多久电话", "总通话时间"],
        "sql_template": "SELECT SUM(talk_duration_seconds) / 60.0 AS total_talk_minutes, SUM(talk_duration_seconds) / 3600.0 AS total_talk_hours FROM fact_calling WHERE org_id = '{org_id}' AND talk_duration_seconds IS NOT NULL AND start_time >= '{start_date}' AND start_time < '{end_date}'",
        "definition_desc": "所有已接通通话的时长总和（分钟/小时）",
        "unit": "分钟 / 小时",
        "category": "通话",
        "table_used": ["fact_calling"],
        "applicable_scenes": ["通话资源消耗", "通信成本分析"],
    },

    # ─── 工作空间指标 ──────────────────────────────────────────
    {
        "metric_id": "workspace_usage_time",
        "metric_name": "工作空间使用时长",
        "aliases": ["使用时间", "活跃时长", "在线时长", "使用平台时间", "workspace时长", "活跃时间"],
        "sql_template": "SELECT SUM(total_active_time_seconds) / 3600.0 AS total_active_hours, AVG(total_active_time_seconds) / 3600.0 AS avg_active_hours_per_user FROM fact_workspace WHERE org_id = '{org_id}' AND record_date >= '{start_date}' AND record_date < '{end_date}'",
        "definition_desc": "用户在工作空间的总活跃时长和人均活跃时长（小时）",
        "unit": "小时",
        "category": "工作空间",
        "table_used": ["fact_workspace"],
        "applicable_scenes": ["用户活跃度", "使用趋势", "部门对比"],
    },
    {
        "metric_id": "login_count",
        "metric_name": "登录次数",
        "aliases": ["登录数", "登录频次", "每天登录几次"],
        "sql_template": "SELECT SUM(login_count) AS total_logins, AVG(login_count) AS avg_logins_per_user FROM fact_workspace WHERE org_id = '{org_id}' AND record_date >= '{start_date}' AND record_date < '{end_date}'",
        "definition_desc": "用户登录系统的总次数和人均登录次数",
        "unit": "次",
        "category": "工作空间",
        "table_used": ["fact_workspace"],
        "applicable_scenes": ["用户粘性", "登录频率分析"],
    },
    {
        "metric_id": "file_activity",
        "metric_name": "文件操作数",
        "aliases": ["文件创建数", "文件编辑数", "文件浏览数", "上传下载数", "文件活动"],
        "sql_template": "SELECT SUM(file_created_count) AS total_created, SUM(file_edited_count) AS total_edited, SUM(file_viewed_count) AS total_viewed, SUM(file_uploaded_count) AS total_uploaded, SUM(file_downloaded_count) AS total_downloaded FROM fact_workspace WHERE org_id = '{org_id}' AND record_date >= '{start_date}' AND record_date < '{end_date}'",
        "definition_desc": "文件创建、编辑、浏览、上传、下载的总次数",
        "unit": "次",
        "category": "工作空间",
        "table_used": ["fact_workspace"],
        "applicable_scenes": ["协作活跃度", "文件使用分析"],
    },
    {
        "metric_id": "task_completion",
        "metric_name": "任务完成数",
        "aliases": ["完成任务数", "创建任务数", "任务完成率", "做了多少任务"],
        "sql_template": "SELECT SUM(task_created_count) AS tasks_created, SUM(task_completed_count) AS tasks_completed, ROUND(SUM(task_completed_count) * 100.0 / NULLIF(SUM(task_created_count), 0), 2) AS completion_rate FROM fact_workspace WHERE org_id = '{org_id}' AND record_date >= '{start_date}' AND record_date < '{end_date}'",
        "definition_desc": "创建的任务数和已完成的任务数及完成率",
        "unit": "个 / %",
        "category": "工作空间",
        "table_used": ["fact_workspace"],
        "applicable_scenes": ["团队生产力", "任务管理效率"],
    },

    # ─── 消息指标 ───────────────────────────────────────────────
    {
        "metric_id": "message_count",
        "metric_name": "消息发送数",
        "aliases": ["发了多少消息", "消息数量", "信息发送数", "发送消息数", "聊天数"],
        "sql_template": "SELECT COUNT(*) AS message_count FROM fact_messaging WHERE org_id = '{org_id}' AND is_deleted = FALSE AND sent_time >= '{start_date}' AND sent_time < '{end_date}'",
        "definition_desc": "指定时间范围内发送的未被删除的消息总数",
        "unit": "条",
        "category": "消息",
        "table_used": ["fact_messaging"],
        "applicable_scenes": ["消息量趋势", "各部门消息量对比", "活跃时段分析"],
    },
    {
        "metric_id": "message_interaction",
        "metric_name": "消息互动数",
        "aliases": ["回复数", " Reactions 数", "收到多少反应", "互动消息数", "已读回执数"],
        "sql_template": "SELECT SUM(reaction_count) AS total_reactions, SUM(CASE WHEN is_reply = TRUE THEN 1 ELSE 0 END) AS reply_count, SUM(read_receipt_count) AS total_read_receipts FROM fact_messaging WHERE org_id = '{org_id}' AND is_deleted = FALSE AND sent_time >= '{start_date}' AND sent_time < '{end_date}'",
        "definition_desc": "消息的反应数、回复数和已读回执数",
        "unit": "次",
        "category": "消息",
        "table_used": ["fact_messaging"],
        "applicable_scenes": ["互动活跃度", "消息质量分析"],
    },
    {
        "metric_id": "active_channels",
        "metric_name": "活跃频道数",
        "aliases": ["活跃群聊数", "活跃频道数量", "有多少群在聊天"],
        "sql_template": "SELECT COUNT(DISTINCT channel_id) AS active_channels FROM fact_messaging WHERE org_id = '{org_id}' AND is_deleted = FALSE AND sent_time >= '{start_date}' AND sent_time < '{end_date}'",
        "definition_desc": "指定时间范围内有消息的频道/群组数量",
        "unit": "个",
        "category": "消息",
        "table_used": ["fact_messaging"],
        "applicable_scenes": ["沟通覆盖面", "群组活跃度"],
    },

    # ─── 设备使用指标 ───────────────────────────────────────────
    {
        "metric_id": "device_distribution",
        "metric_name": "设备使用分布",
        "aliases": ["设备分布", "用什么设备", "手机电脑使用率", "设备类型分布"],
        "sql_template": "SELECT device_type, os_platform, COUNT(DISTINCT user_id) AS user_count, SUM(total_active_time_seconds) / 3600.0 AS total_hours FROM fact_device_usage WHERE org_id = '{org_id}' AND record_date >= '{start_date}' AND record_date < '{end_date}' GROUP BY device_type, os_platform ORDER BY total_hours DESC",
        "definition_desc": "按设备类型（desktop/mobile/tablet）和操作系统统计用户数和使用时长",
        "unit": "人 / 小时",
        "category": "设备",
        "table_used": ["fact_device_usage"],
        "applicable_scenes": ["设备偏好分析", "客户端优化决策"],
    },
    {
        "metric_id": "storage_usage",
        "metric_name": "存储空间使用",
        "aliases": ["存储使用量", "用了多少空间", "磁盘使用", "空间使用率"],
        "sql_template": "SELECT SUM(storage_used_mb) / 1024.0 AS total_storage_gb, AVG(storage_used_mb) / 1024.0 AS avg_storage_gb_per_user FROM fact_workspace WHERE org_id = '{org_id}' AND record_date >= '{start_date}' AND record_date < '{end_date}'",
        "definition_desc": "用户工作空间的存储空间总使用量和人均使用量（GB）",
        "unit": "GB",
        "category": "工作空间",
        "table_used": ["fact_workspace"],
        "applicable_scenes": ["存储成本分析", "容量规划"],
    },

    # ─── 综合质量指标 ───────────────────────────────────────────
    {
        "metric_id": "quality_overall",
        "metric_name": "综合质量评分",
        "aliases": ["整体质量", "服务质量", "网络质量评分", "体验评分", "quality score"],
        "sql_template": "SELECT AVG(quality_score) AS avg_quality_score, AVG(avg_latency_ms) AS avg_latency, AVG(avg_packet_loss_rate) * 100 AS avg_packet_loss_pct, AVG(avg_jitter_ms) AS avg_jitter FROM fact_quality WHERE org_id = '{org_id}' AND record_date >= '{start_date}' AND record_date < '{end_date}'",
        "definition_desc": "综合质量评分（0-100）、平均延迟（ms）、平均丢包率（%）、平均抖动（ms）",
        "unit": "分（0-100）/ ms / %",
        "category": "质量",
        "table_used": ["fact_quality"],
        "applicable_scenes": ["整体体验监控", "网络质量趋势", "SLA 合规"],
    },
    {
        "metric_id": "connection_failure_rate",
        "metric_name": "连接失败率",
        "aliases": ["失败率", "连接失败次数", "连接问题", "断线率"],
        "sql_template": "SELECT SUM(connection_failures) AS total_failures, SUM(total_sessions) AS total_sessions, ROUND(SUM(connection_failures) * 100.0 / NULLIF(SUM(total_sessions), 0), 3) AS failure_rate FROM fact_quality WHERE org_id = '{org_id}' AND record_date >= '{start_date}' AND record_date < '{end_date}'",
        "definition_desc": "连接失败次数和连接失败率",
        "unit": "次 / %",
        "category": "质量",
        "table_used": ["fact_quality"],
        "applicable_scenes": ["稳定性监控", "故障预警"],
    },
]
